const fs = require('fs');
const path = require('path');

function processDir(dir) {
  const entries = fs.readdirSync(dir, { withFileTypes: true });
  
  for (const entry of entries) {
    const fullPath = path.join(dir, entry.name);
    
    if (entry.isDirectory()) {
      if (entry.name === '__next.!KGFkbWluKQ') {
        // We found the route group directory generated by Next.js
        // Now recursively find all .txt files inside it
        const txtFiles = findTxtFiles(fullPath);
        for (const txtFile of txtFiles) {
          // txtFile is absolute path
          // We need the relative path from __next.!KGFkbWluKQ
          const relPath = path.relative(fullPath, txtFile);
          // e.g. "reports\__PAGE__.txt" -> "reports.__PAGE__.txt"
          const dotName = '__next.!KGFkbWluKQ.' + relPath.split(path.sep).join('.');
          
          const newPath = path.join(dir, dotName);
          console.log(`Copying ${txtFile} -> ${newPath}`);
          fs.copyFileSync(txtFile, newPath);
        }
      }
      processDir(fullPath);
    }
  }
}

function findTxtFiles(dir) {
  let results = [];
  const entries = fs.readdirSync(dir, { withFileTypes: true });
  for (const entry of entries) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      results = results.concat(findTxtFiles(full));
    } else if (full.endsWith('.txt')) {
      results.push(full);
    }
  }
  return results;
}

processDir(path.join(__dirname, 'out'));
console.log('RSC Payload paths fixed!');
