// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'iOS Firebase 미설정: Firebase Console > 프로젝트 설정 > 앱 추가(iOS)를 완료하세요.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwcjhD8ZT28cy-kk2dPoKC5zDCWHAhyPI',
    appId: '1:545863599367:web:68d1f6050293258217f1a2',
    messagingSenderId: '545863599367',
    projectId: 'cleancare-cf307',
    authDomain: 'cleancare-cf307.firebaseapp.com',
    storageBucket: 'cleancare-cf307.firebasestorage.app',
    measurementId: 'G-XLT5YGZXMK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9drNluRpRXy2qU--PurgVPxtXL7yccKs',
    appId: '1:545863599367:android:1468b99cd78b32f817f1a2',
    messagingSenderId: '545863599367',
    projectId: 'cleancare-cf307',
    storageBucket: 'cleancare-cf307.firebasestorage.app',
  );

}